server:
  # Render/Railway etc. provide PORT; locally default to 8080
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always  # ensure schema.sql + data.sql run (even outside embedded DBs)

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # Simple CORS via properties (no code changes).
  # Set CORS_ALLOWED_ORIGINS env on Render to your frontend URL, e.g. https://pookieshop-web.onrender.com
  mvc:
    cors:
      mappings:
        "[/api/**]":
          allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: false
          max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
