-- Reset tables for H2 in-memory (drop first, then recreate)
DROP TABLE IF EXISTS shop_order;
DROP TABLE IF EXISTS wishlist;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS product;

-- === Products ===
CREATE TABLE product (
  id BIGINT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  description VARCHAR(1000),
  price DECIMAL(10,2) NOT NULL,
  category VARCHAR(100),
  image_url VARCHAR(500)
);

-- === Reviews ===
CREATE TABLE review (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,
  rating INT NOT NULL,
  text VARCHAR(1000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- === Wishlist ===
CREATE TABLE wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_wishlist UNIQUE (user_id, product_id)
);

-- === Orders (used by MOCK checkout too) ===
CREATE TABLE shop_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razorpay_order_id VARCHAR(64),     -- stays nullable; unused in mock
  amount_paise INT NOT NULL,
  currency VARCHAR(10),
  receipt VARCHAR(50),
  status VARCHAR(32),                -- CREATED | PAID | FAILED
  payment_id VARCHAR(64),
  signature VARCHAR(255),
  customer_name VARCHAR(120),
  email VARCHAR(120),
  phone VARCHAR(32),
  address1 VARCHAR(200),
  address2 VARCHAR(200),
  city VARCHAR(100),
  state VARCHAR(100),
  pincode VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
